# Generated by Django 2.2.7 on 2021-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desajono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
